add: openapiの作成
kaaaaakun/ft_transcendence pull request #17
Opened 2024-08-29 11:29 UTC by kaaaaakun

2024-08-29 11:30 UTC, kaaaaakun commented
[エディター](https://editor.swagger.io/)に貼り付ければ、一応内容を確認できます。

2024-08-30 06:49 UTC, jizots commented on openapi.yaml
> +  /tournaments:
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
apiで想定しているpathは /tmt/newl/ です！
省略形にしているのは、テーブル名の秘匿性を高める、コーディングの冗長性を減らす、URIが長くて打ちたくたい（笑）、という理由からです。
/newl/が付与されているのは、URI /tmt/は、トーナメントテーブル単体のAPI（GET：トーナメント全体を取得する、POST：トーナメントテーブルを1行足す）に利用しているので、利用できないためです〜。
なので何かしらの変更はMustだと考えていますが、思いを聞くためにaskラベルにしました。

2024-08-30 06:57 UTC, jizots commented on openapi.yaml
> +      # example:
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
exampleはコメントアウトしていてOKですか？
モックサーバーで、/tournaments/のレスポンスを見ると、フロントに渡してもエラーになりそうなデータでした。
あとはAPIチームで綺麗にしてってことかしら？

2024-08-30 07:35 UTC, tkuramot commented on openapi.yaml
> +  /tournaments:
@jizots 
assignされてたので横入りしちゃいます

![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
> テーブル名の秘匿性を高める

SQLインジェクションを念頭に置いてる感じですか？
もしそうなら根本的な解決ではなくて効果が限定的になりそうなので、開発のときのわかりやすさとかを優先してtournamentsにしてもいいのかなと思いました

> /newl/が付与されているのは、URI /tmt/は、トーナメントテーブル単体のAPI（GET：トーナメント全体を取得する、POST：トーナメントテーブルを1行足す）に利用している

`POST /tmt/newl`と`POST /tmt`って何が違うんですか？

2024-08-30 08:32 UTC, kaaaaakun commented on openapi.yaml
> +      # example:
これ、確かにコメントアウトない方がいいですね。
修正します。

2024-08-30 08:39 UTC, kaaaaakun commented
> リクエスト、レスポンスの形式もレビューの対象ですか？

使うのはフロントなので、対象にしてOKです。

2024-08-30 09:05 UTC, kaaaaakun commented
@jizots
論点が色々になってるのですが、自分のわかる範囲だけ答えます！
> apiで想定しているpathは /tmt/newl/ です！

このurlの話ってmiroの
```
トーナメントを始める：/api/tmt/newl/ (new local tournament)
対戦を始める：/api/mtch/strt/ (start)
得点が入った: /api/mtch/iscr/ (increment score)
```
この部分ですよね？
見落としてました。

ただ、RESTの設計思想に倣うなら、もう少しURLはわかりやすい方がいいかと思います。
↓[その辺の記事](https://www.strategit.jp/column/041304/)の引用
```
ひと目でAPIと分かるURLにする
URLにAPIのバージョンを含める
URLには動詞を含めず複数形の名詞だけで構成する
アプリケーションにファイルの拡張子は含めない
リソースの関連性がひと目で分かること
```

今回の場合だと
```
トーナメントを始める POST：/api/tournaments/local/new
トーナメントを取得するGET：/api/tournaments/local
対戦を始めるGET：/api/matches/local/
得点が入ったPUT: /api/matches/local/score
```
とかの方がいいと思っていますが、いかがでしょう？

(あと、version管理の概念については今回は導入していません。
本当なら`/api/v1/tournaments/local/new`となるようです。)

2024-08-30 09:11 UTC, jizots commented on openapi.yaml
> +  /tournaments:
> SQLインジェクションを念頭に
はい、根本的にSQLインジェクションはエスケープで解決されているので、これはあくまで限定的な効果だと思います。

> POST /tmt/newlとPOST /tmtって何が違うんですか？
期待している内容と一致しないかもしれませんが、とりあえず👇です。
それぞれ期待しているリクエストBodyの内容、バックエンドでの内部処理、レスポンスが違います。
``POST /tmt/newl``: トーナメントを始めるボタンで呼び出され、"players":{"name1", "name2"}のような参加者名をリクエストで送信して、複数のDBテーブルに情報を書き込み、トーナメント待機画面に必要な情報をレスポンスします。
``POST /tmt``: 一般ユーザーの利用は想定していません（100％開発では使うかも）。{num_of_player: x, status:"X"}のような情報をリクエストで送信して、トーナメントテーブルに情報を書き込み、書き込まれた行をレスポンスします。

2024-08-30 09:34 UTC, jizots commented
> @jizots 論点が色々になってるのですが、自分のわかる範囲だけ答えます！
> 
> > apiで想定しているpathは /tmt/newl/ です！
> 
> このurlの話ってmiroの
> 
> ```
> トーナメントを始める：/api/tmt/newl/ (new local tournament)
> 対戦を始める：/api/mtch/strt/ (start)
> 得点が入った: /api/mtch/iscr/ (increment score)
> ```
> 
> この部分ですよね？ 見落としてました。
> 
> ただ、RESTの設計思想に倣うなら、もう少しURLはわかりやすい方がいいかと思います。 ↓[その辺の記事](https://www.strategit.jp/column/041304/)の引用
> 
> ```
> ひと目でAPIと分かるURLにする
> URLにAPIのバージョンを含める
> URLには動詞を含めず複数形の名詞だけで構成する
> アプリケーションにファイルの拡張子は含めない
> リソースの関連性がひと目で分かること
> ```
> 
> 今回の場合だと
> 
> ```
> トーナメントを始める POST：/api/tournaments/local/new
> トーナメントを取得するGET：/api/tournaments/local
> 対戦を始めるGET：/api/matches/local/
> 得点が入ったPUT: /api/matches/local/score
> ```
> 
> とかの方がいいと思っていますが、いかがでしょう？
> 
> (あと、version管理の概念については今回は導入していません。 本当なら`/api/v1/tournaments/local/new`となるようです。)

それに変更します！
くらもとさんの意見と合わせて、そっちの方がわかりやすいと思うので。
トーナメントを始める POST：/api/tournaments/local/　(new不要：POST = Create)
トーナメントを取得するGET：/api/tournaments/local/ 
対戦を始めるGET：/api/matches/local/
得点が入ったPUT: /api/matches/local/score/

2024-08-30 12:09 UTC, tkuramot commented on openapi.yaml
> +              $ref: "#/components/schemas/ScoreRequest"
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
スコアの差分を渡すならpostの方がいいかもしれない。putは冪等な処理？

https://developer.mozilla.org/ja/docs/Glossary/Idempotent

2024-08-30 12:57 UTC, kaaaaakun commented
一旦これで完成でいいと思っていますが、いかがでしょう？

2024-08-30 13:33 UTC, jizots commented on openapi.yaml
> +    TournamentResponse:
![must-badge](https://img.shields.io/badge/review-must-red.svg)
レスポンス形式がちょい違うことに今さら気づいた。。sorry
```
{ "1": {
       "player": { "name":"Alice" },
       "tournamentplayer": {"victory_count":1},
       "next_player":true },
   "2": {
      "player": { "name":"Bob" },
       "tournamentplayer": {"victory_count":0},
       "next_player":true } }
```

2024-08-30 13:39 UTC, jizots commented on openapi.yaml
> +    MatchResponse:
![must-badge](https://img.shields.io/badge/review-must-red.svg)
こちらも
```
{ "1": {
　　"player":{ "name": "Alice" },
　　"matchdetail": { "player_id": 1, "match_id": 1, "score": 0 },
   "2": {
　　"player":{ "name":"Bob" },
 　　"matchdetail": { "player_id": 2, "match_id": 1, "score": 0 }}
    }
}
 ```

2024-08-30 13:42 UTC, jizots commented on openapi.yaml
> +    ScoreRequest:
![must-badge](https://img.shields.io/badge/review-must-red.svg)
ここまでの計3つを要変更です〜
{ "matchdetail": { "match_id": 1, "player_id": 1 } }

2024-08-30 13:49 UTC, jizots requested changes
リクエストもしくはレスポンスの形式が設計と違ってました！（この観点で見るの忘れてましたすみません）

2024-08-30 13:49 UTC, tkuramot commented on openapi.yaml
> +              tournamentplayer:
スネークケースにしてるやつと単語をそのまま繋げてるやつが混在してるのが気になりました

2024-08-30 13:59 UTC, jizots commented on openapi.yaml
> +              tournamentplayer:
JSONのキーのことですかね？DBの設計に合わせています。”そのままつなげてるやつ”はテーブル名で、”スネークケース”はキー（テーブルの項目）です。

2024-08-30 16:02 UTC, kaaaaakun commented on openapi.yaml
> +    TournamentResponse:
この辺、わざとやっていて、伝えるの忘れてました。
すみません。

変更した理由
1. jsonのkeyを動的することは避けられるべきことのようです。
今回の例と必ずしも同じではないかもしれないですが、[参考](https://watson-developer-cloud.github.io/api-guidelines/#avoid-dynamic-keys)

3. ただ数字を振っているだけで、不要なIDかなと思いました。

4. 配列の場合の方が、loop回すのも若干楽かなと。
- 配列の場合の書き方
```
let participants = [
  { "name": "Alice" },
  { "name": "Bob" }
];

// 配列メソッドを使ってアクセスする
participants.forEach(participant => console.log(participant.name));
// 出力: Alice, Bob
```
- 動的な場合の書き方
```
let data = {
  "1": { "name": "Alice" },
  "2": { "name": "Bob" }
};

// for...in ループを使ってすべてのnameを表示する
for (let key in data) {
  console.log(data[key].name);
}
```

間違いがあるかもしれないですが、上のような認識で変更してました。
元の設計でも、大きな問題はないかと思うので、戻した方が良さそうであれば戻します。

2024-08-30 16:09 UTC, kaaaaakun commented on openapi.yaml
> +    ScoreRequest:
これも、伝え忘れで申し訳ないです。

matchdetailというデータ構造は下記のものを指すので、同じ名前は避けたいと削除しました。
```
    MatchDetail:
      type: object
      properties:
        player_id:
          type: integer
        match_id:
          type: integer
        score:
          type: integer
```

基本的にはなくてもいいかと思うのですが、
もし、まとめた名前が必要なら、scoreInclementとかですかね、、、？

2024-08-30 20:54 UTC, jizots commented on openapi.yaml
> +    TournamentResponse:
@soma0822  @tkuramot 
この点、フロント要望が元なので、フロントに判断お任せします！
3つのBoby（トーナメント時画面を表示するためのAPIレスポンス（特にここ）、対戦画面を表示するためのAPIレスポンス、得点が入った時のAPIリクエスト）の内容が、最初の設計と変わってますが、フロントのロジックは対応できそうですかね？

2024-08-31 16:16 UTC, tkuramot commented on openapi.yaml
> +              tournamentplayer:
DBに合わせる必要は必ずしもないと思っていて、統一しても良さそうな気がしてます
明日話しましょう

2024-09-01 05:15 UTC, tkuramot commented on openapi.yaml
> +              tournamentplayer:
[memo]
DBのテーブル名とともにスネークケースにする

2024-09-02 09:18 UTC, kaaaaakun commented
現在の問題点
- トーナメントのレスポンスにend_tournamentが必要かどうか (ガッキー待ち)

2024-09-03 01:35 UTC, jizots commented on openapi.yaml
> +  /tournaments:
分かりにくいと評判のため、フルスペルのURIを利用する。
POST /tmt/newlとPOST /tmtの違いの説明終わり。
Close

2024-09-03 04:07 UTC, kaaaaakun commented
> > 現在の問題点
> > 
> > * トーナメントのレスポンスにend_tournamentが必要かどうか (ガッキー待ち)
> 
> ごめんなさい。そもそも何でend_matchって入れたんでしたっけ。 ”フロントかバックのどちらかだけで判定する”ため？

そうです！
終了判定をバックエンドに依存するために導入しました。

> フロント的には合ってもなくても処理はそんな変わらない気するけど、トーナメントもどちらかの判定にして、トーナメントのステータスに不整合が起きないようにするには合ったほうが良さそう？
多分、end_matchの話(終了判定をどちらがするか)という話とは違くて、
tournamentの終了判定には影響がない。
だけど、フロントがtournamentの情報を取得したときに、何をもって終了と判定するかがいまいち不明だったので、追加してもいいかなと思いました。

end_tournamentがない今の状態だと、next_playerが全員falseの場合がトーナメントが終了って判定になるかなって思っている。
```
{
	"participants": [
		{
			"player": {
				"name": "Alice"
			},
			"tournament_players": {
				"victory_count": 0
			},
			"next_player": false
		},
		{
			"player": {
				"name": "Bob"
			},
			"tournament_players": {
				"victory_count": 1
			},
			"next_player": true
		},
		{
			"player": {
				"name": "Charlie"
			},
			"tournament_players": {
				"victory_count": 0
			},
			"next_player": true
		},
		{
			"player": {
				"name": "David"
			},
			"tournament_players": {
				"victory_count": 1
			},
			"next_player": false
		}
	]
}
```
ただ、それを全部フロントで判定する意味あるかなと思って、end_tournament一つあれば解決？と思って提案してみた。

お任せします〜

2024-09-03 14:44 UTC, soma0822 commented
> > > 現在の問題点
> > > 
> > > * トーナメントのレスポンスにend_tournamentが必要かどうか (ガッキー待ち)
> > 
> > 
> > ごめんなさい。そもそも何でend_matchって入れたんでしたっけ。 ”フロントかバックのどちらかだけで判定する”ため？
> 
> そうです！ 終了判定をバックエンドに依存するために導入しました。
> 
> > フロント的には合ってもなくても処理はそんな変わらない気するけど、トーナメントもどちらかの判定にして、トーナメントのステータスに不整合が起きないようにするには合ったほうが良さそう？
> > 多分、end_matchの話(終了判定をどちらがするか)という話とは違くて、
> > tournamentの終了判定には影響がない。
> > だけど、フロントがtournamentの情報を取得したときに、何をもって終了と判定するかがいまいち不明だったので、追加してもいいかなと思いました。
> 
> end_tournamentがない今の状態だと、next_playerが全員falseの場合がトーナメントが終了って判定になるかなって思っている。
> 
> ```
> {
> 	"participants": [
> 		{
> 			"player": {
> 				"name": "Alice"
> 			},
> 			"tournament_players": {
> 				"victory_count": 0
> 			},
> 			"next_player": false
> 		},
> 		{
> 			"player": {
> 				"name": "Bob"
> 			},
> 			"tournament_players": {
> 				"victory_count": 1
> 			},
> 			"next_player": true
> 		},
> 		{
> 			"player": {
> 				"name": "Charlie"
> 			},
> 			"tournament_players": {
> 				"victory_count": 0
> 			},
> 			"next_player": true
> 		},
> 		{
> 			"player": {
> 				"name": "David"
> 			},
> 			"tournament_players": {
> 				"victory_count": 1
> 			},
> 			"next_player": false
> 		}
> 	]
> }
> ```
> 
> ただ、それを全部フロントで判定する意味あるかなと思って、end_tournament一つあれば解決？と思って提案してみた。

まあ、next_playerが全員falseか、victory_countの合計が"人数-1"で判定で十分な気がする

2024-09-04 06:12 UTC, kaaaaakun commented
end_tournamentは入れない方針になりました。

2024-09-04 08:32 UTC, jizots approved these changes

2024-09-05 12:29 UTC, merged