docker-composeのドラフトを作成
kaaaaakun/ft_transcendence pull request #3
Opened 2024-08-13 11:57 UTC by soragogo

ボリューム名は各々で決めたいかもしれないのでコメントアウトしています

2024-08-14 01:11 UTC, jizots commented on docker-compose.yml
> +# volumes:
名称決定は各チーム依存でもいいと思いましたが、ばらつきがなくなるような工夫があるとより良さそうです〜。
例えばボリュームはvol_xxxと命名すること、とコメントしておくとか！

2024-08-14 01:24 UTC, jizots commented on docker-compose.yml
> +
networksディレクティブが必要です！
各コンテナが通信できるように、ネットワークを1つ作成しましょう〜
で、コンテナのうちweb以外には、作成したネットワークを持たせましょう（inceptionと同じです！）

2024-08-14 01:30 UTC, jizots commented on docker-compose.yml
> +      context: web/
ディレクトリはnginx/ですね

2024-08-14 01:31 UTC, jizots requested changes
作成ありがとうございます！
どゆこと？とかほんとに？ってところがあればディスカッションしましょう！
local.ymlについては意見はほとんど同じです！

2024-08-14 05:24 UTC, soragogo commented
レビューありがとうございます！めっちゃ穴だらけでした笑
夜修正して出します！（目標）

2024-08-16 02:11 UTC, jizots requested changes
ボリュームは了解です〜。networksだけ一部削除したら完了ですね！

2024-08-16 04:01 UTC, soragogo commented
> ボリュームは了解です〜。networksだけ一部削除したら完了ですね！

すみません、これどれでしょうか！

2024-08-16 04:16 UTC, jizots commented on docker-compose.yml
> +    networks:
webのネットワークは不要ですね〜。ほかのコンテナと通信しないはずなので！

2024-08-16 04:48 UTC, jizots approved these changes

2024-08-16 05:22 UTC, merged