Api businesslogic stanby image
kaaaaakun/ft_transcendence pull request #31
Opened 2024-09-01 14:48 UTC by soma0822

プレイヤー名（複数）をJSONで受け取って、内部でDBに登録（プレイヤー登録、トーナメント登録だけ）して、JSONでデータをレスポンスする機能を実装

2024-09-02 05:07 UTC, jizots commented on api/conf/app_tournament/views.py
> +        player_names = request.data.getlist('players')
![must-badge](https://img.shields.io/badge/review-must-red.svg)
/tournament/local/　でPOSTするとgetlistでエラーになります〜。
前の状態に戻すと動作します。

2024-09-02 05:18 UTC, jizots commented on api/conf/app_tournament/tests.py
> +class TournamentPlayerSerializerTest(BaseTestSetup):
APITestCaseを継承してないので、twoplayerなどのテストが実行されてないっぽいですね。継承すると、テストでエラーになります！

2024-09-02 05:20 UTC, jizots requested changes
作成ありがとうございます！一旦こんな感じでした〜。
getlistに変更した意図があるなら、getに戻すことで別の問題が起きるのかも？

2024-09-02 08:37 UTC, jizots commented on api/conf/app_match/utils.py
> +        matchdetail1 = register_matchdetail(validate_matchdetail_data(match.id, player1.id, 0, 'await'))
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
```suggestion
        matchdetail1 = register_matchdetail(validate_matchdetail_data(match.id, player1.id, 0, 'await'))
```
ここか意図しない動作を発生させるかもです〜。
player1はtournament_playerのインスタンスですよね。なので、player1.idは”tournament_player”テーブルのidだと思います。
ただ、validate_matchdetail_data()は”player”テーブルのidを期待してます。
なので、player1.idではなく、player1.player_idが正しいかも。
ちらっと見て思ったので検証してません。。

2024-09-02 14:34 UTC, soma0822 commented on api/conf/app_match/utils.py
> +        matchdetail1 = register_matchdetail(validate_matchdetail_data(match.id, player1.id, 0, 'await'))
です。ありがとうございます

2024-09-03 01:30 UTC, jizots commented on api/conf/app_match/utils.py
> +        matchdetail1 = register_matchdetail(validate_matchdetail_data(match.id, player1.player_id, 0, 'await'))
![must-badge](https://img.shields.io/badge/review-must-red.svg)
testでエラーになりますね〜。
player1.player_id -> player1.player_id.id が正しそうです。（keyを渡してるつもりがオブジェクトを渡してたみたいです。内部挙動がよくわからん、、、）
testを走らせたり、ブラウザからデータを投げて検証したりしてみてくださいな！

> 
======================================================================
ERROR: test_eight_players (tournament.tests.LocalTournamentViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/trans/match/utils.py", line 17, in create_match
    matchdetail1 = register_matchdetail(validate_matchdetail_data(match.id, player1.player_id, 0, 'await'))
  File "/trans/match/utils.py", line 36, in validate_matchdetail_data
    if matchdetail_serializer.is_valid(raise_exception = True):
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 231, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'player_id': [ErrorDetail(string='Incorrect type. Expected pk value, received Player.', code='incorrect_type')]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/trans/tournament/tests.py", line 194, in test_eight_players
    match, matchdetail1, matchdetail2 = create_next_tournament_match(tournament.id)
  File "/trans/tournament/utils.py", line 64, in create_next_tournament_match
    return create_match(tournament_id, tournamentplayers[0], tournamentplayers[1])
  File "/trans/match/utils.py", line 20, in create_match
    raise ValidationError(e.detail)
rest_framework.exceptions.ValidationError: {'player_id': [ErrorDetail(string='Incorrect type. Expected pk value, received Player.', code='incorrect_type')]}

======================================================================
ERROR: test_four_players (tournament.tests.LocalTournamentViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/trans/match/utils.py", line 17, in create_match
    matchdetail1 = register_matchdetail(validate_matchdetail_data(match.id, player1.player_id, 0, 'await'))
  File "/trans/match/utils.py", line 36, in validate_matchdetail_data
    if matchdetail_serializer.is_valid(raise_exception = True):
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 231, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'player_id': [ErrorDetail(string='Incorrect type. Expected pk value, received Player.', code='incorrect_type')]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/trans/tournament/tests.py", line 140, in test_four_players
    match, matchdetail1, matchdetail2 = create_next_tournament_match(tournament.id)
  File "/trans/tournament/utils.py", line 64, in create_next_tournament_match
    return create_match(tournament_id, tournamentplayers[0], tournamentplayers[1])
  File "/trans/match/utils.py", line 20, in create_match
    raise ValidationError(e.detail)
rest_framework.exceptions.ValidationError: {'player_id': [ErrorDetail(string='Incorrect type. Expected pk value, received Player.', code='incorrect_type')]}

======================================================================
ERROR: test_two_palyers (tournament.tests.LocalTournamentViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/trans/tournament/tests.py", line 120, in test_two_palyers
    sorted(response.data['participants'], key=lambda x: x['player']['name']),
KeyError: 'participants'

----------------------------------------------------------------------
Ran 18 tests in 0.080s

FAILED (errors=3)
Destroying test database for alias 'default'...

2024-09-03 01:32 UTC, jizots requested changes
testでエラー吐いたので、原因を見つけてコメントしときました〜

2024-09-03 14:37 UTC, soma0822 commented on api/conf/app_match/utils.py
> +        matchdetail1 = register_matchdetail(validate_matchdetail_data(match.id, player1.player_id, 0, 'await'))
ごめんなさい。完全に寝ぼけてました。
昨日のlog見たらテストが失敗しているlogがおもいっきり残っていました。

2024-09-03 21:12 UTC, jizots approved these changes

2024-09-03 21:13 UTC, merged